### ISSUE TITLE
Any plans to revive this project?

### ISSUE THREAD

**Issue by arioch** [voxpupuli/puppetdb-ruby#12]
With only a single release - 0.0.1 even - and the last commit being pushed 2 years ago it doesn't seem to be very alive.
Any plans to revive this and more specifically to support PuppetDB API v4?

**Comment by bilsch** [comment]
:+1:

**Comment by andrewfraley** [comment]
@arioch @bilsch if you need to use API v4, try my example in https://github.com/puppetlabs/puppetdb-ruby/issues/13

You basically have to modify the URL and specify the API version

**Comment by arioch** [comment]
@andrewfraley excellent, thanks!

**Comment by rlinehan** [comment]
![](http://i.memecaptain.com/gend_images/0sK5xw.jpg)

We've transferred ownership to [voxpupuli](https://voxpupuli.org/)! So it's much more alive than it was before.

**Comment by dhollinger** [comment]
I've begun work on reviving this project and getting it up to date.

**Comment by dhollinger** [comment]
Release 1.0.0 published to rubgems: https://rubygems.org/gems/puppetdb-ruby
