### ISSUE TITLE
API V4 Example

### ISSUE THREAD

**Issue by andrewfraley** [voxpupuli/puppetdb-ruby#13]
You can get this to work with API V4.  I'll submit a PR against the documentation.

```
client = PuppetDB::Client.new({
    :server => 'https://localhost:8081/pdb/query',
    :pem    => {
        'key'     => "keyfile",
        'cert'    => "certfile",
        'ca_file' => "cafile"
    }}, 4)
```

**Comment by arioch** [comment]
:+1:

**Comment by ncorrare** [comment]
Tried it in latest PE, still would require some refactoring around the paths:

localhost - - [28/Mar/2016:16:14:17 +0000] "GET /v4/nodes?query=%22node.name%22 HTTP/1.1" 404 0 "-" "Ruby"
localhost - - [28/Mar/2016:16:15:08 +0000] "GET /pdb/query/v4/nodes/node.name HTTP/1.1" 200 948 "-" "curl/7.29.0"

**Comment by andrewfraley** [comment]
@ncorrare note the  `:server => 'https://localhost:8081/pdb/query', ` in my example prefixes the new path

**Comment by ncorrare** [comment]
Yeah, just saw it and tried it! In my defence I'm sick!

**Comment by walkleyn** [comment]
I keep getting "The v3 API has been retired; please use v4" when I try doing a request with the /pdb/query path included. Anything I'm missing (this is via non-ssl connection)

**Comment by dhollinger** [comment]
Latest updates to master connect to API v4 by default
