### ISSUE TITLE
cannot load such file -- puppetdb

### ISSUE THREAD

**Issue by jacobmw** [voxpupuli/puppetdb-ruby#33]
I have installed the gem:
gem list --local | grep puppetdb
puppetdb-ruby (1.1.1)

and in my code I have 
require 'puppetdb'

however, I am getting the following error:
Failure/Error: require 'puppetdb'

LoadError:
  cannot load such file -- puppetdb

**Comment by dhollinger** [comment]
@jacobmw 

How is your environment setup? Do you have any additional information you can give me that may help?

I am unable to duplicate the error you're seeing in my code or with irb.

**Comment by jacobmw** [comment]
Oh boy, realizing that comment of mine was not that helpful.  I also can’t even say for sure where I was getting this error.  I’m guessing it was part of some spec tests I was writing.  I’ll have to add more details the next time I come across this.
