### ISSUE TITLE
Only GET requests supported

### ISSUE THREAD

**Issue by robinbowes** [voxpupuli/puppetdb-ruby#4]
It appears that the current code only supports GET requests, ie. queries.

I want to use the /commands endpoint, ie. I need to send POST requests.

Are there any plans to extend puppetdb-ruby to support POST requests? If I write code would you consider including it?

R.

**Comment by dhollinger** [comment]
Closing due to age. Please re-open if this is still an issue

**Comment by robinbowes** [comment]
Looks like post functionality was implemented at some stage.
