### ISSUE TITLE
No way to retrieve all facts/nodes

### ISSUE THREAD

**Issue by ccaum** [voxpupuli/puppetdb-ruby#8]
There's no way to query all facts and nodes using the PuppetDB::Client#request method. The method must take a query as the second parameter to the method call.  However, it should be possible to just specify 'nodes' or 'facts' as the first parameter with no other parameters to retrieve all the nodes or facts respectively.

**Comment by dhollinger** [comment]
@ccaum I'm closing this due to age. Let me know if you still have issues
